{{ config(materialized='ephemeral') }}

WITH RAW_REVIEWS AS
(
    --SELECT * FROM AIRBNB.RAW.RAW_REVIEWS            -- DIRECT REFERENCE TO TABLE
    SELECT * FROM {{ source('airbnb', 'reviews') }}   -- REFERENCE TO SOURCE
)

SELECT 
    LISTING_ID,
    DATE AS REVIEW_DATE,
    REVIEWER_NAME,
    COMMENTS AS REVIEW_TEXT,
    SENTIMENT AS REVIEW_SENTIMENT
FROM RAW_REVIEWS