{{ config(materialized='ephemeral') }}

WITH RAW_LISTINGS AS
(
    -- SELECT * FROM AIRBNB.RAW.RAW_LISTINGS            -- DIRECT REFERENCE TO TABLE
     SELECT * FROM {{ source('airbnb', 'listings') }}   -- REFERENCE TO SOURCE
)

SELECT 
    ID AS LISTING_ID,
    NAME AS LISTING_NAME,
    LISTING_URL,
    ROOM_TYPE,
    MINIMUM_NIGHTS,
    HOST_ID,
    PRICE AS PRICE_STR,
    CREATED_AT,
    UPDATED_AT
FROM RAW_LISTINGS